resolver: lts-18.21
packages:
  - .
  - sandbox
extra-deps:
  - tree-monad-0.3.1
  - git: https://github.com/LeventErkok/sbv.git
    commit: 58f13c937cb8d6847e84c2b1ed3be35f39897526
  - libBF-0.6.2
  - git: https://github.com/GaloisInc/what4.git
    commit: c8e6381b9a4c635c70939ac55de1369e9444b77d
    subdirs:
      - what4
  - bv-sized-1.0.3
  - config-value-0.8.2
  - panic-0.4.0.1
  - parameterized-utils-2.1.4.0
  - zenc-0.1.2
  - bitwise-1.0.0.1
  - OneTuple-0.3.1
  - hashable-1.3.5.0
